[package]
name = "toy_cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.1"
image = "0.24.7"
rand = "0.8.5"
rayon = "1.7.0"
tobj = "4.0.0"
